channels:
  - anaconda
  - conda-forge
  - defaults

dependencies:
  - coverage
  - GitPython
  - h5py
  - matplotlib
  - numpy
  - pandas
  - pillow
  - pip
  - psutil
  - pytest
  - requests
  - ruamel.yaml
  - scikit-learn
  - scipy
  - sphinx
  - urllib3
  - xarray
  - pip:
    - tox
    - sphinx-gallery
    - argschema
    - xmljson
    - bumpversion
    - cookiecutter
